/*
 Navicat Premium Data Transfer

 Source Server         : spotify
 Source Server Type    : PostgreSQL
 Source Server Version : 140010 (140010)
 Source Host           : localhost:5432
 Source Catalog        : aydym
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 140010 (140010)
 File Encoding         : 65001

 Date: 25/01/2024 03:14:06
*/


-- ----------------------------
-- Table structure for dashboard_country
-- ----------------------------
DROP TABLE IF EXISTS "public"."dashboard_country";
CREATE TABLE "public"."dashboard_country" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "name_tm" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "name_ru" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "image" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "modified" timestamptz(6) NOT NULL,
  "updated_by_id" int4
)
;

-- ----------------------------
-- Indexes structure for table dashboard_country
-- ----------------------------
CREATE INDEX "dashboard_country_updated_by_id_a06789a3" ON "public"."dashboard_country" USING btree (
  "updated_by_id" "pg_catalog"."int4_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table dashboard_country
-- ----------------------------
ALTER TABLE "public"."dashboard_country" ADD CONSTRAINT "dashboard_country_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Foreign Keys structure for table dashboard_country
-- ----------------------------
ALTER TABLE "public"."dashboard_country" ADD CONSTRAINT "dashboard_country_updated_by_id_a06789a3_fk_auth_user_id" FOREIGN KEY ("updated_by_id") REFERENCES "public"."auth_user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
