# Generated by Django 4.2.3 on 2024-01-24 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/albums/%Y/%m/%d')),
                ('year', models.IntegerField(default=2023)),
                ('trend', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '015. Albums',
                'verbose_name_plural': '015. Albums',
            },
        ),
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200)),
                ('name_tk', models.CharField(max_length=200, null=True)),
                ('name_ru', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='images/audiobooks/%Y/%m/%d')),
                ('description', models.TextField()),
                ('description_tk', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('author', models.CharField(max_length=200)),
                ('author_tk', models.CharField(max_length=200, null=True)),
                ('author_ru', models.CharField(max_length=200, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/books/%Y/%m/%d')),
            ],
            options={
                'verbose_name': '045. Audiobook',
                'verbose_name_plural': '045. Audiobook',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200)),
                ('name_tk', models.CharField(max_length=200, null=True)),
                ('name_ru', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(default='', upload_to='images/countries')),
            ],
            options={
                'verbose_name': '003. Countries',
                'verbose_name_plural': '003. Countries',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200)),
                ('name_tk', models.CharField(max_length=200, null=True)),
                ('name_ru', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='images/genres/%Y/%m/%d')),
            ],
            options={
                'verbose_name': '020. Genres',
                'verbose_name_plural': '020. Genres',
            },
        ),
        migrations.CreateModel(
            name='PlaylistCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200)),
                ('abbre', models.CharField(max_length=10)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': '035. PlaylistCategory',
                'verbose_name_plural': '035. PlaylistCategory',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/songs/%Y/%m/%d')),
                ('listened_count', models.IntegerField(default=0, verbose_name='Listened count')),
                ('hit', models.BooleanField(default=False)),
                ('audio', models.FileField(upload_to='audio/songs/%Y/%m/%d')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='app.album')),
                ('genres', models.ManyToManyField(blank=True, related_name='songs', to='app.genre')),
            ],
            options={
                'verbose_name': '025. Songs',
                'verbose_name_plural': '025. Songs',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200)),
                ('name_tk', models.CharField(max_length=200, null=True)),
                ('name_ru', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='images/playlist/%Y/%m/%d')),
                ('order', models.IntegerField(default=1)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlists', related_query_name='playlists', to='app.playlistcategory')),
                ('songs', models.ManyToManyField(blank=True, null=True, related_name='playlists', related_query_name='playlists', to='app.song')),
            ],
            options={
                'verbose_name': '040. Playlist',
                'verbose_name_plural': '040. Playlist',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(default='', upload_to='images/artists/%Y/%m/%d')),
                ('artist_of_the_week', models.BooleanField(default=False)),
                ('countries', models.ManyToManyField(related_name='artists', to='app.country')),
            ],
            options={
                'verbose_name': '010. Artists',
                'verbose_name_plural': '010. Artists',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(related_name='albums', to='app.artist'),
        ),
        migrations.CreateModel(
            name='Song_Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.IntegerField(default=1)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', related_query_name='songs', to='app.artist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', related_query_name='artists', to='app.song')),
            ],
            options={
                'verbose_name': '030. Artists Songs',
                'verbose_name_plural': '030. Artists Songs',
                'unique_together': {('song', 'artist')},
            },
        ),
    ]
