# Generated by Django 4.2.3 on 2024-01-24 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_album_artists_remove_playlist_songs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiobook',
            old_name='author_tk',
            new_name='author_tm',
        ),
        migrations.RenameField(
            model_name='audiobook',
            old_name='description_tk',
            new_name='description_tm',
        ),
        migrations.RenameField(
            model_name='audiobook',
            old_name='name_tk',
            new_name='name_tm',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='name_tk',
            new_name='name_tm',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='name_tk',
            new_name='name_tm',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='name_tk',
            new_name='name_tm',
        ),
    ]
