# Generated by Django 4.2.3 on 2024-01-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_author_tk_audiobook_author_tm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='listened_count',
            field=models.IntegerField(default=0),
        ),
    ]
