# Generated by Django 4.2.3 on 2024-01-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_artist_listened_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
