# Generated by Django 4.2.3 on 2024-01-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_song_audio_alter_song_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(related_name='songs', to='app.genre'),
        ),
    ]
